# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Temple of the Unticketed"
description: A Burning Man project by members of NYC Resistor

email: info@templeoftheunticketed.net
#blog logo
#logo: "/assets/images/df_logo.jpg"
# blog cover
#cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"
cover: "/assets/images/header-totu.jpg"

name: 'Temple of the Unticketed'
author: 'Temple of the Unticketed'
author_image: "/assets/images/author.jpg"

max-bio: "Hardware/firmware hacker"
justin-bio: "Project Lead, Web Guru, Backend"

paginate:	5

url: "http://www.templeoftheunticketed.net" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  # - icon:	twitter
  #   url:	https://twitter.com/sgentiluomo
  #   desc: Follow me on twitter
  #   share_url: http://twitter.com/share
  #   share_title: ?text=
  #   share_link: "&amp;url="

  # - icon:	instagram
  #   url:	https://instagram.com/sgentiluomo
  #   desc: Follow me on instagram
  #   share_url:
  #   share_title:
  #   share_link:

  - icon:	github
    url:	https://github.com/nycresistor/TotU
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
